### ISSUE TITLE
PA Review: Authentication

### ISSUE THREAD

**Issue by dmccapes4** [dmccapes4/eat_time#1]
- [x] Backend authentication
- [x] Frontend authentication

**Comment by anastassia-b** [comment]
The functionality works well! Here are some comments to fix in order to complete the MVP:

- [ ] To show that a user is logged in, add a `Welcome, username` to the nav bar to the left of the logout button.
- [ ] Remove nav bar from under the splash image since the functionality is already in that component.
- [ ] Add demo button to the nav bar.
- [ ] Password is shows in plain text at the moment.
- [ ] Change to `Invalid username or password`
- [ ] Have the logo link back to the splash page. 
- [ ] Increase the resolution of the EatTime logo on the splash page.
- [ ] Currently there's multiple fonts. I would stick with 2, mainly using a sans-serif font (like Arial, or the one on your buttons) for most text. This includes the text in your modal, the search fields, and the search results, please make it consistent.
