### ISSUE TITLE
PA Review: Reservations

### ISSUE THREAD

**Issue by dmccapes4** [dmccapes4/eat_time#3]

**Comment by anastassia-b** [comment]
The functionality is great! I can make a reservation based on my search parameters and pick a time from the options displayed. Making a reservation takes me to my reservations profile, where I can also see past reservations. Question-- should users be able to delete past reservations? Yes if they want to clear their history, but you can also decide to not let them. 

- [ ] Updating a reservation works to update what is viewed on the reservations page. Sometimes, If I try to update twice, I notice that my original inputs are all still in the form instead of the updated fields. But sometimes it works..
- [ ] On "future reservations" change "Delete Reservation" button to "Cancel Reservation" to be more semantic. 
- [ ] The `time-input search-btn` has two arrow dropdowns on the update reservation view, should only be 1. Also, remove the `Find a Table` button from reservation updates, should only appear in the initial search bar. 

Please fix these when you have time. Otherwise this MVP is complete.
