### ISSUE TITLE
PA Review: Ratings/Reviews

### ISSUE THREAD

**Issue by dmccapes4** [dmccapes4/eat_time#4]

**Comment by anastassia-b** [comment]
Great work on this feature! I can see the list of reviews on the home page and also under my profile of reservations. The starts are a really nice touch. A few things:

- [ ] Creating and deleting a review on past reservations works great. Updating a review does not work yet, doesn't dispatch a `RECIEVE_REVIEW` action nor update the review. 
- [ ] Add usernames to the reviews to see who they are by on the restaurant show page.
- [ ] The styling of the reviews container could be improved a bit. For example, giving it a title "Reviews" and giving the index container a margin could be good. Also, the page could extend to fill the content of the restaurant show instead of having 3 scrollbars. I can meet with you in person today about this.

**Comment by anastassia-b** [comment]
Great, you fixed updating reviews by refactoring your UpdateReview component to have an internal state, which updates when the form input changes. The updateReview action then takes the This is a good pattern to follow for all React forms (creating, updating) in general.
